apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, applications, , */, allow
    p, role:admin, repositories, , */, allow
    p, role:admin, projects, , */, allow
    g, my-admin-group, role:admin
    g, my-readonly-group, role:readonly
  scopes: '[groups]'
