apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-app
  template:
    metadata:
      labels:
        app: budget-app
    spec:
      containers:
        - name: budget-app
          image: <your-dockerhub-username>/budget-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_NAME
              value: budget_app
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: budget-app
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: budget-app
